### ISSUE TITLE
change to use state_machine gem?

### ISSUE THREAD

**Issue by ShiningRay** [nyarly/sockjs-ruby#5]
[state_machine](https://github.com/pluginaweek/state_machine) provides more features such as transition events.
and if users define methods with the same name as those defined in state modules, it won't override them.

**Comment by nyarly** [comment]
I'm not sure I see the advantage of making a change at this point. In general, FSMs using modules are kind of a pain in Ruby - if anything I'd want states to be simple objects with delegation.
